[options]
addons_path = /mnt/extra-addons,/mnt/odoo-priv,/mnt/tutorials,/mnt/Pruebas,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = myDB19
db_user = chrizzzadmin
db_password = 051002
db_port = 5432
admin_passwd = $pbkdf2-sha512$600000$IWQMAYBQ6l1rLWVs7T1HqA$OE7ajMmKP7eWE6jn7979gGiOm6pL6wV5Xk/EXCh9wM.qVJSMrh7xPQ3/I3A2yYqVpzYUsqWz2MzCSZMMrKul5g

