[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = myDB19
db_user = admin
db_password = admin
db_port = 5432
admin_passwd = $pbkdf2-sha512$600000$sNYaY8y5NyZkjBECYKw15g$bQN5j3NccJ1E2U4RR1uZk6cA0KJSPdFmnds4f7TV3UhIQ2YFhAy6WSjJQt5/7FcTSziiaVp/Xi/ty.O8Ck8fIA

