{
    'name': 'Menus Production-Aprobacion formulas',
    'version': '1.0',
    'category': 'Production Testing',
    'summary': 'Menus Production Management',
    'depends': ['base','hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/principal_menu.xml',
        'views/produccion_menu.xml',
        'views/planeamiento_menu.xml',
        'views/control_calidad_menu.xml',
        'views/costos_menu.xml',
        'views/costos_mantenimiento.xml',
        'views/mantenimiento_menu.xml',
        'views/mantenimiento_clasificadores.xml',
        'views/mantenimiento_configuracion.xml',
        'views/mantenimiento_configuracion_codigoBarras.xml',
        'views/mantenimiento_consultas.xml',
        'views/mantenimiento_reportes.xml',
        'views/produccion_reportes.xml',
        'views/produccion_reportes_insumos.xml',
        'views/utils_menu.xml',
        'views/program_162_formula_aprobacion.xml',
    ]
}
