{
    'name': 'Menus Production',
    'version': '1.0',
    'category': 'Production Testing',
    'summary': 'Menus Production Management',
    'depends': ['base'],
    'data': [
        #'security/ir.model.access.csv',
        'views/principal_menu.xml',
        'views/produccion_menu.xml',
        'views/planeamiento_menu.xml',
        'views/control_calidad_menu.xml',
        'views/costos_menu.xml',
        'views/costos_mantenimiento.xml',
        'views/mantenimiento_menu.xml',
        'views/mantenimiento_clasificadores.xml',
        'views/mantenimiento_configuracion.xml',
        'views/mantenimiento_configuracion_codigo_barras.xml',
        'views/mantenimiento_consultas.xml',
        'views/mantenimiento_reportes.xml',
        'views/produccion_reportes.xml',
        'views/produccion_reportes_insumos.xml',
        #'views/ayuda_sistemas.xml',
        #'views/codigo_barras.xml',
        #'views/costeo_batch.xml',
        #'views/formulas_menu.xml',
        #'views/sig_logistica.xml',
        #'views/utilidades_menu.xml',
        'views/utils_menu.xml',
    ]
}
